web/router.ex
defmodule Entice.Web.Router do
  use Entice.Web.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    # Manually inject the layout here due to non standard namespaces...
    plug :put_layout, {Entice.Web.LayoutView, "app.html"}
  end

  # Web routes
  scope "/", Entice.Web do
    pipe_through :browser # Use the default browser stack

    get "/",             PageController, :index
    get "/auth",         PageController, :auth
    get "/client/:map",  PageController, :client
    get "/register",     PageController, :account
    get "/invitation",   PageController, :invitation
    get "/friend",       PageController, :friend
  end


  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
  end

  # API routes
  scope "/api", Entice.Web do
    pipe_through :api

    post    "/login",                 AuthController,     :login
    post    "/logout",                AuthController,     :logout

    get     "/char",                  CharController,     :list
    post    "/char",                  CharController,     :create

    get     "/maps",                  DocuController,     :maps
    get     "/skills",                DocuController,     :skills
    get     "/skills/:id",            DocuController,     :skills

    get     "/token/entity",          TokenController,    :entity_token

    get     "/account/by_char_name",  AccountController,  :by_char_name
    post    "/account/register",      AccountController,  :register
    post    "/account/request",       AccountController,  :request_invite

    get     "/friend",                FriendsController,  :index
    post    "/friend",                FriendsController,  :create
    delete  "/friend",                FriendsController,  :delete
  end
end

web/templates/page/account.html.eex
<div>
  <form id="createAccountForm" name="createAccountForm">
    <fieldset>
      <legend>Account</legend>
      <p>
        <label>Create a new Account</label>
      </p>
      <p>
        <label for="email" class="inputLabel">Email:</label>
        <input type="text" class="inputField" id="email" name="email" value="" size="20" maxlength="50" />
      </p>
      <p>
        <label for="password" class="inputLabel">Password:</label>
        <input type="password" class="inputField" id="password" name="password" value="" size="20" maxlength="32" />
      </p>
      <p>
        <label class="inputLabel">Key:</label>
        <input type="text" class="inputField" id="key" name="key" value="" size="20" maxlength="36">
    </fieldset>
    <input type="submit" class="inputButton" id="submit" name="submit" value="... do it ..." />
  </form>
  <script>
    $(".email").focus();

    $('#createAccountForm').submit(function(e){
      e.preventDefault();
    });

    $('#submit').click(function(){
      email = $("#email").val();
      passw = $("#password").val();
      key = $("#key").val();

      $.ajax("<%= account_path(@conn, :register) %>", {
        type: 'POST',
        contentType: 'application/json',
        dataType: 'json',
        data: JSON.stringify({"email": email, "password": passw, "invite_key": key}),
        cache: false
      })
      .done(function(data){
        $('.authMessage').append("<br/>").append(data.message);
        // then log in
        $.ajax("<%= auth_path(@conn, :login) %>", {
          type: "POST",
          contentType: "application/json",
          data: JSON.stringify({"email": email, "password": passw, "client_version": "<%= @client_version %>"})
        })
        .done(function(data) {
          $('.authMessage').append(data.message);
          $('.authMessage').append('<br/><a href="<%= page_path(@conn, :index) %>">... go back ...</a>');
          $(location).attr('href','<%= page_path(@conn, :index) %>');
        })
      })
      .fail(function(data) {
        $('.authMessage').append(data.message);
        $('.authMessage').append("<br/>Please try again!");
      });
    });
  </script>
</div>

<br>
<div class="authMessage"></div>

web/templates/page/auth.html.eex
<%= if logged_in?(@conn) do %>
   <form action="<%= auth_path(@conn, :logout) %>" id="searchForm">

    <input type="submit" class="inputButton" name="" value="... log out ..." />

    <script>
      $(".inputButton").focus();

      $("#searchForm").submit(function(event) {
        event.preventDefault();

        $.post("<%= auth_path(@conn, :logout) %>")
         .then(function(data) {
          if (data.status === "ok") {
            $('.authMessage').append(data.message);
            $('.authMessage').append('<br/><a href="<%= page_path(@conn, :index) %>">... go back ...</a>');
            $(location).attr('href','<%= page_path(@conn, :index) %>');
          } else {
            $('.authMessage').append(data.message);
            $('.authMessage').append("<br/>Please try again!");
          }
        });
      });


    </script>

  </form>
<% else %>
  <form action="<%= auth_path(@conn, :login) %>" id="searchForm">

    <fieldset><legend>Login</legend>
      <p>
        <label for="email" class="inputLabel">Email:</label>
        <input type="text" class="inputField" id="email" name="email" value="" size="20" maxlength="50" />
      </p>
      <p>
        <label for="password" class="inputLabel">Password:</label>
        <input type="password" class="inputField" id="password" name="password" value="" size="20" maxlength="32" />
      </p>
    </fieldset>

    <input type="submit" class="inputButton" name="" value="... do it ..." />

    <script>
      $("#email").focus();

      $("#searchForm").submit(function(event) {
        event.preventDefault();
        $('.authMessage').empty();

        var $form = $(this),
          email = $form.find("input[name='email']").val(),
          passw = $form.find("input[name='password']").val();

        $.ajax("<%= auth_path(@conn, :login) %>", {
          type: "POST",
          contentType: "application/json",
          data: JSON.stringify({"email": email, "password": passw, "client_version": "<%= @client_version %>"})
        })
        .done(function(data) {
          $('.authMessage').append(data.message);
          $('.authMessage').append('<br/><a href="<%= page_path(@conn, :index) %>">... go back ...</a>');
          $(location).attr('href','<%= page_path(@conn, :index) %>');
        })
        .fail(function(data) {
          $('.authMessage').append(data.message);
          $('.authMessage').append("<br/>Please try again!");
        });
      });
    </script>

  </form>
<% end %>

<br>
<div class="authMessage"></div>

web/templates/page/client.html.eex
<div class="outputTextbox" id="output"></div>

<script>
  function puts(header, headerColor, message) {
    var pre = document.createElement("p");
    pre.style.wordWrap = "break-word";
    pre.innerHTML = '<span style="color: ' + headerColor + '">' + header + ':</span> ' + message;
    $('#output').append(pre);
  };

  <!-- TODO: get character name from account -->
  $.get("<%= raw token_path(@conn, :entity_token, map: @map, char_name: "Test Char") %>")
   .then(function(data) {
    if (data.status === "ok") {
      puts("Message", "Green", JSON.stringify(data.message));
      puts("Client", "DarkGreen", JSON.stringify(data.client_id));
      puts("Entity", "DarkGreen", JSON.stringify(data.entity_id));
      puts("Token", "DarkGreen", JSON.stringify(data.entity_token));
      init("<%= @map %>", data.client_id, data.entity_id, data.entity_token)
    } else {
      $(location).attr('href','<%= page_path(@conn, :index) %>');
    }
  });

  function init(map, client_id, entity_id, entity_token) {
    var socket = new Phoenix.Socket("/socket");
    socket.connect({client_id: client_id, entity_token: entity_token, map: map});

    socket.channel("entity:" + map)
    .join()
    .receive("join:ok", function(payload) {
      puts("[entity] Joined", "Blue", JSON.stringify(payload))
    })
    .receive("entity:add", function(payload) {
      puts("[entity] Got", "Red", JSON.stringify(payload))
    })
    .receive("entity:remove", function(payload) {
      puts("[entity] Got", "Red", JSON.stringify(payload))
    });

    socket.channel("group:" + map)
    .join()
    .receive("join:ok", function(payload) {
      puts("[group] Joined", "Blue", JSON.stringify(payload))
    });


    socket.channel("skill:" + map)
    .join()
    .receive("join:ok", function(payload) {
      puts("[skill] Joined", "Blue", JSON.stringify(payload))
      //channel.send("skillbar:set", {slot: 1, id: 3});
    })
    .receive("skillbar:ok", function(payload) {
      puts("[skill] Got", "Red", JSON.stringify(payload))
    });

    socket.channel("social:" + map + ":group:" + entity_id)
    .join()
    .receive("join:ok", function(payload) {
      puts("[social] Joined", "Blue", JSON.stringify(payload))
    });
  };

</script>

web/templates/page/error.html.eex
Something went wrong

web/templates/page/friend.html.eex
<%= if logged_in?(@conn) do %>

  <fieldset>
    <legend>Friends list</legend>
    <p>Friends:</p>
    <p id="friends"></p>
    <p>
      <label for="name" class="inputLabel">Name:</label>
      <input type="text" class="inputField" id="name" name="name" value="" size="20" maxlength="50" />
    </p>
    <input type="submit" class="inputButton" id="submitAdd" name="submit" value="Add Friend" />
    <input type="submit" class="inputButton" id="submitDel" name="submit" value="Delete Friend" />
    <p id="message"></p>
  </fieldset>

  <script>
    var $friends = $("#friends");
    var $message = $("#message");

    $.ajax("<%= friends_path(@conn, :index) %>", {
        type: 'GET'
      })
      .done(function(data) {
        if(data.status == "ok"){
          for (i = 0; i < data.friends.length; i++) {
            friend = data.friends[i];
            if (friend.base_name != friend.current_name){
              $friends.append(friend.base_name + " (" + friend.current_name + ") [" + friend.status + "]<br>");
            }
            else {
              $friends.append(friend.base_name + " [" + friend.status + "]<br>");
            }
          }
        }
        else {
        }
      })
      .fail(function(data) {});

    $('#submitAdd').click(function() {
      name = $("#name").val();

      $.ajax("<%= friends_path(@conn, :create) %>", {
        type: 'POST',
        contentType: 'application/json',
        dataType: 'json',
        data: JSON.stringify({"char_name": name}),
        cache: false
      })
      .done(function(data) {
        if(data.status == "ok"){
        }
        else {
        }
        $message.append("<br>" + data.message);
      })
      .fail(function(data) {
      });
    });

    $('#submitDel').click(function() {
      name = $("#name").val();

      $.ajax("<%= friends_path(@conn, :delete) %>", {
        type: 'DELETE',
        contentType: 'application/json',
        dataType: 'json',
        data: JSON.stringify({"char_name": name}),
        cache: false
      })
      .done(function(data) {
        if(data.status == "ok"){
        }
        else {
        }
        $message.append("<br>" + data.message);
      })
      .fail(function(data) {
      });
    });



  </script>
<% else %>
  <p>You need to be Logged in... </p>
<% end %>

web/templates/page/index.html.eex
... welcome to entice ...

web/templates/page/invitation.html.eex
<%= if logged_in?(@conn) do %>
  <fieldset>
    <legend>Request Invitation</legend>
    <p>
      <label>Invite a Friend...</label>
    </p>
    <p>
      <label for="email" class="inputLabel">Email:</label>
      <input type="text" class="inputField" id="email" name="email" value="" size="20" maxlength="50" />
    </p>
    <input type="submit" class="inputButton" id="submit" name="submit" value="Request key" />
  </fieldset>
  <script>
    $('#submit').click(function() {
      email = $('#email').val();

      $.ajax("<%= account_path(@conn, :request_invite) %>", {
        type: 'POST',
        contentType: 'application/json',
        dataType: 'json',
        data: JSON.stringify({"email": email}),
        cache: false
      })
      .done(function(data) {

        if(data.status == "error"){
          $('.authMessage').append("<br/> " + data.message);
        }
        else {
          $('.authMessage').append("<br/> Invitation is created.");
          $('.authMessage').append("<br/> Email: " + data.email);
          $('.authMessage').append("<br/> InviteKey: " + data.key);
          $('.authMessage').append("<br/><p>This is the link<br/><a href=\"mailto:" + data.email + "?subject=You%20are%20invited%20to%20play%20on%20a%20Guild%20Wars%20private%20Server&body=Hello,%20you%20are%20invited%20to%20play%20on%20the%20Entice%20GuildWars%20Server&body=Use%20your%20Email%20and%20the%20following%20Key%20to%20Register%20at%20<%=page_url(@conn, :account)%>%20InvitationKey:%20" + data.key + 
            "target=\"top\">Send as Mail</p></a>");
        }
      })
      .fail(function(data) {
        $('.authMessage').append(data.message);
        $('.authMessage').append("<br/>Please try again!");
      });
    });
  </script>
<% else %>
  <p>You need to be Logged in... </p>
<% end %>

<br>
<div class="authMessage"></div>

web/templates/page/not_found.html.eex
The page you are looking for does not exist